version: '3.8'
services:
  rest-api:
    container_name: rest-api
    # our container is going to restart unless we explicitly stop it
    restart: unless-stopped
    # build in the root directory
    build:
      context: ./node-app
    # expose our port in format HOST:CONTAINER
    ports:
      - 8081:8081
      
  # *****************************   
  postgresql-db:
    image: postgres:10
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=DemoPa$$
      - POSTGRES_USER=demouser
      - POSTGRES_DB=demodb

      
  # *****************************
  spring-boot-app:
    restart: always
    container_name: springboot-postgresql
    image: springboot-postgresql
    build: ./spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - postgresql-db
    
      
volumes:
  postgres-data:
